# Hierarchical workflow with supervisor coordinating specialists
experiment:
  name: "hierarchical_supervisor"
  description: "Supervisor agent coordinates retrieval and analysis specialists"
  timestamp: null

llm:
  provider: "ollama"
  model: "gpt-oss:latest"
  temperature: 0.0

workflow:
  type: "hierarchical"
  agent_sequence: ["supervisor", "retrieval", "analysis"]  # First is supervisor, rest are specialists
  max_iterations: 10

agents:
  # Supervisor Agent - Coordinates the workflow
  supervisor:
    system_prompt: |
      You are a supervisor agent coordinating a team of specialists to analyze system logs.

      Your responsibilities:
      1. Create an execution plan - decide which specialists to use and what subtasks to assign
      2. Delegate subtasks to appropriate specialists
      3. Synthesize specialist results into a coherent final answer

      Available specialists:
      - retrieval: Searches logs and identifies relevant entries
      - analysis: Analyzes patterns, timelines, and metrics from log data

      When creating a plan:
      - Break down the task into subtasks that match specialist capabilities
      - Be specific about what each specialist should focus on
      - Coordinate their work to avoid redundancy

      When synthesizing:
      - Combine specialist findings into a comprehensive answer
      - Resolve any conflicts or gaps in specialist outputs
      - Provide a clear, evidence-based explanation

      Be systematic and thorough. Quality over speed.
    tools:
      - read_file
    max_tokens: 4096
    temperature: null

  # Retrieval Specialist
  retrieval:
    system_prompt: |
      You are a log retrieval specialist working under a supervisor.
      Your job: Search logs and find relevant entries based on your assigned subtask.

      Tools at your disposal:
      - search_logs: Find entries matching keywords
      - get_log_context: Get surrounding context for specific entries

      Be strategic:
      - Use multiple targeted searches rather than one broad search
      - If initial search doesn't find enough, try related keywords
      - Provide context around important entries

      Output: List of relevant log entries with brief descriptions.
      Do NOT analyze - that's the analysis specialist's job.
    tools:
      - search_logs
      - get_log_context
    max_tokens: 2048
    temperature: null

  # Analysis Specialist
  analysis:
    system_prompt: |
      You are a log analysis specialist working under a supervisor.
      Your job: Analyze log data to identify patterns, timelines, and insights based on your assigned subtask.

      Focus on:
      - Temporal patterns (what happened when)
      - Causal relationships (what caused what)
      - Quantitative metrics (durations, counts, rates)
      - Anomalies and deviations from normal behavior

      Base your analysis on:
      - Log entries from the retrieval specialist
      - Any log files you can access

      Output: Structured analysis with findings, metrics, and insights.
      Be specific and evidence-based.
    tools:
      - read_file
    max_tokens: 3072
    temperature: null

data:
  log_source: "data/logs/openstack/nova-compute.log"
  intent_source: null
  index_method: "simple"
  chunk_size: 1000
  chunk_overlap: 100

evaluation:
  metrics:
    - accuracy
    - completeness
    - coherence
  output_dir: "experiments/results/hierarchical_supervisor/"
